# Generated by Django 5.2 on 2025-04-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcodesession',
            name='secret',
            field=models.CharField(default='ui', max_length=100),
        ),
    ]
